export const FETCH_NEWS_Initiate = "FETCH_NEWS_Initiate";
export const FETCH_NEWS_START = "FETCH_NEWS_START";
export const FETCH_NEWS_HEALTH = "FETCH_NEWS_HEALTH";
export const FETCH_NEWS_BUSINESS = "FETCH_NEWS_BUSINESS";
export const FETCH_NEWS_TECHNOLOGY = "FETCH_NEWS_TECHNOLOGY";
export const FETCH_NEWS_SPORTS = "FETCH_NEWS_SPORTS";
export const FETCH_NEWS_END = "FETCH_NEWS_END";

export const STORE_DETAILS_PAGE_INIT = "STORE_DETAILS_PAGE_INIT";
export const STORE_DETAILS_PAGE = "STORE_DETAILS_PAGE";
export const GET_DETAILS_PAGE_INIT = "GET_DETAILS_PAGE_INIT";
export const GET_DETAILS_PAGE = "GET_DETAILS_PAGE";

export const SEARCH_INIT = "SEARCH_INIT";
export const SEARCH_START = "SEARCH_START";
export const SEARCH_SET_PAGE = "SEARCH_SET_PAGE";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
export const SEARCH_RESULTS = "SEARCH_RESULTS";
export const SEARCH_END = "SEARCH_END";
export const SEARCH_CLEAR_DATA = "SEARCH_CLEAR_DATA";
